#test cases for pTFCE
require("oro.nifti")
context("true signal")
#test_file("../report.log")

test_that("Volume with spherical signal and random noise, SNR=1", {

  expected=readNIfTI("../../data/test02A_out.nii.gz")
  smooth=read.table("../../data/test02A_smoothness.txt"); # file generated by FSL smoothest

  ptfce=-log(ptfce(img = readNIfTI("../../data/test02A_in.nii.gz"),
              V=smooth[2,2],
              Rd = smooth[1,2]*smooth[2,2],
              mask = readNIfTI("../../data/test02_mask.nii.gz"),
              verbose = F
  )$pTFCE)

  expect_equal(mean(ptfce), mean(expected))
  expect_equal(sd(ptfce), sd(expected))
  expect_equal(ptfce[10,10,10], expected[10,10,10]) #background
  expect_equal(ptfce[47,32,16], expected[47,32,16]) #true signal
})

test_that("Volume with spherical signal and random noise, SNR=2", {

  expected=readNIfTI("../../data/test02B_out.nii.gz")
  smooth=read.table("../../data/test02B_smoothness.txt"); # file generated by FSL smoothest

  ptfce=-log(ptfce(img = readNIfTI("../../data/test02B_in.nii.gz"),
                   V=smooth[2,2],
                   Rd = smooth[1,2]*smooth[2,2],
                   mask = readNIfTI("../../data/test02_mask.nii.gz"),
                   verbose = F
  )$pTFCE)

  expect_equal(sd(ptfce), sd(expected))
  expect_equal(ptfce[10,10,10], expected[10,10,10]) #background
  expect_equal(ptfce[47,32,16], expected[47,32,16], tolerance = 1.2e-05) #true signal
})

test_that("Volume with spherical signal and random noise, SNR=3", {

  expected=readNIfTI("../../data/test02C_out.nii.gz")
  smooth=read.table("../../data/test02C_smoothness.txt"); # file generated by FSL smoothest

  ptfce=-log(ptfce(img = readNIfTI("../../data/test02C_in.nii.gz"),
                   V=smooth[2,2],
                   Rd = smooth[1,2]*smooth[2,2],
                   mask = readNIfTI("../../data/test02_mask.nii.gz"),
                   verbose = F
  )$pTFCE)

  expect_equal(mean(ptfce), mean(expected))
  expect_equal(sd(ptfce), sd(expected))
  expect_equal(ptfce[10,10,10], expected[10,10,10]) #background
  expect_equal(ptfce[47,32,16], expected[47,32,16], tolerance = 1.2e-05) #true signal
})
